<?php


use App\Http\Guzzle\Sgp\Get\Responses\LeagueViewsResponse;
use Illuminate\Support\Collection;

class LeagueViewsResponseTest extends \Tests\TestCase
{
    protected LeagueViewsResponse $response;

    public function setUp(): void
    {
        $this->response = new LeagueViewsResponse(new \Tests\Mocks\SgpLeagueViewsMock());
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function it_gets_a_response()
    {
        $this->assertNotNull($this->response->getRawResponse());
    }

    /** @test */
    public function it_returns_a_member_list_collection()
    {
        $this->assertInstanceOf(Collection::class, $this->response->memberList());
    }

    /** @test */
    public function it_searches_for_a_member_by_discord_id()
    {
        $this->assertNotNull($this->response->findMemberByDiscordId('324060102770556933'));
    }
}
